name: my-tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2 

    # Установка Poetry
    - name: Install Poetry
      run: |
        # Скачиваем и устанавливаем инструмент Poetry
        curl -sSL https://install.python-poetry.org | python3 -
        # Добавляем путь к установленному Poetry в переменную окружения PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Установка зависимостей
    - name: Install dependencies
      run: |
        # Устанавливаем зависимости проекта через Poetry
        poetry install

    # Запуск линтера
    - name: Run make lint
      run: |
        # Запускаем линтер кода через make команду
        make lint

    # Запуск тестов и запись кода завершения
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      if: github.ref_name == 'main'
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
          debug: true
